### ISSUE TITLE
error while loading shared libraries: libmicrohttpd.so.10

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree#105]
After upgrading libmicrohttpd from 0.9.44-1 to 0.9.48-1 on archlinux, eth stopped working.

```
 ~ $ eth --frontier --listen 30304
eth: error while loading shared libraries: libmicrohttpd.so.10: cannot open shared object file: No such file or directory
 ~ $ ll /usr/lib/libmicrohttpd*
   0 lrwxrwxrwx 1 root root  24 Feb  5 11:28 /usr/lib/libmicrohttpd.so -> libmicrohttpd.so.12.36.0
   0 lrwxrwxrwx 1 root root  24 Feb  5 11:28 /usr/lib/libmicrohttpd.so.12 -> libmicrohttpd.so.12.36.0
100K -rwxr-xr-x 1 root root 99K Feb  5 11:28 /usr/lib/libmicrohttpd.so.12.36.0
```

Using the latest git through webthree-umbrella.

```
 ~ $ pacaur -Q ethereum-git
ethereum-git 1.0rc2.r117.g58d2a77-1
 ~ $ uname -a
Linux x230 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
```

I tried to recompile after the lib update, but the issue persists. Somehow webthree hardlinks the wrong (non-existent) library. Any idea why?

**Comment by 5chdn** [comment]
@LefterisJP you are also using ArchLinux, did you update libmicrohttpd to v0.9.48-1 yet? can you reproduce this and/or have any clue why this still links against the old lib?

For reference, https://aur.archlinux.org/packages/ethereum/

And: ArchLinux bug tracker rejected this because AUR packages are not supported. If anyone could give me a hint what might be causing this, I could try to squash this bug. The Arch community will thank you.

**Comment by LefterisJP** [comment]
@5chdn Let me have a look today.

**Comment by LefterisJP** [comment]
So I reproduced your issue. The problem is that libethereum is trying to link to both versions of libmicrohttpd:

``` sh
$: ldd libethereum/libethereum.so | grep libmicrohttpd   
        libmicrohttpd.so.12 => /usr/lib/libmicrohttpd.so.12 (0x00007ff0426eb000)
        libmicrohttpd.so.10 => not found
```

We don't have anything like that in the cmake files so the problem is not with us. Sure enough looking at one of the direct dependencies of libethereum, `libjson-rpc-cpp` we can find the culprit.

``` sh
$: ldd /usr/lib/libjsonrpccpp-server.so.0 

        linux-vdso.so.1 (0x00007ffcbcd67000)
        libjsonrpccpp-common.so.0 => /usr/lib/libjsonrpccpp-common.so.0 (0x00007f8336e01000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8336be4000)
        libmicrohttpd.so.10 => not found
        libjsoncpp.so.1 => /usr/lib/libjsoncpp.so.1 (0x00007f83369ac000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f833662a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f8336414000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f833606f000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x000055df62eef000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f8335d71000)
```

So libjsonrpccpp-server is pointing to the old libmicrohttpd. That's AUR for you :(
But the fix is then easy and requires no code changes what so ever.  Just remove libjsonrpc-cpp and reinstall it.

Assuming you are using yaourt:

``` sh
yaourt -Rs libjson-rpc-cpp-git 
yaourt -S libjson-rpc-cpp-git 
```

And sure enough now libethereum only has one link to limicrohttpd.

``` sh
ldd libethereum/libethereum.so | grep libmicrohttpd     
        libmicrohttpd.so.12 => /usr/lib/libmicrohttpd.so.12 (0x00007f77056fe000)
```

**Comment by 5chdn** [comment]
Thanks, indeed, that worked.

**Comment by cinemast** [comment]
It is also fixed in AUR now. You can just upgrade without removing the package first.

**Comment by LefterisJP** [comment]
thanks @cinemast for your work on libjson-rpc-cpp :)
Good to know it's also fixed in the AUR.

**Comment by saschafr** [comment]
I still have a problem related to this one (at least, I guess). When installing via "yaourt libjson-rpc-cpp-git" I get the following message:
The following tests FAILED:
4 - connector_http (Failed)
7 - integration (Failed)
8 - all (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: **\* [test] Error 8
==> ERROR: A failure occurred in check().
Aborting...
Is this another problem or related with this one?

**Comment by LefterisJP** [comment]
Arch Linux packages get upgraded really regularly and git versions may be broken due to upstream problems.
Try to switch back to the non git version of the package, so 

```
yaourt -Rs libjson-rpc-cpp-git
yaourt -S libjson-rpc-cpp
```

**Comment by bobsummerwill** [comment]
I don't think there is any work left here.

Please re-open as an issue against webthree-umbrella if there is anything left here, @5chdn.  Thanks!

BTW ... see http://docs.ethereum.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/linux-arch-aur.html.    If there is more you would like to say about this, please create a PR against https://github.com/bobsummerwill/homestead-guide, and I will get that merged into the Homestead docs.

**Comment by bobsummerwill** [comment]
I will be migrating the Wiki build instructions from webthree-umbrella there too very soon.

http://docs.ethereum.org/en/latest/ethereum-clients/cpp-ethereum/index.html

**Comment by 5chdn** [comment]
Will look into it, thanks for pointing out
